# -*- mode: ruby -*-
# vi: set ft=ruby :

# # Vagrant 1.7+ automatically inserts a different
# # insecure keypair for each new VM created. The easiest way
# # to use the same keypair for all the machines is to disable
# # this feature and rely on the legacy insecure key.
# # config.ssh.insert_key = false
Vagrant.configure("2") do |config|

    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://atlas.hashicorp.com/search.
    config.vm.box = "ubuntu/trusty64"

    # Synced folder configuration 
    if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
        config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
    else
        config.vm.synced_folder ".", "/vagrant"
    end

    # Common domain configuration
    config.vm.provider "virtualbox" do |domain|
	domain.customize ["modifyvm", :id, "--nic2", "hostonly"]
        domain.customize ["modifyvm", :id, "--hostonlyadapter2", "vboxnet1"]
    end

    # Machine-nodes specific definition
    config.vm.define "identity-node1" do |vmconfig|
      	vmconfig.vm.hostname = "identity-node1"
        vmconfig.vm.network :private_network, ip: "172.16.76.2", netmask: "28"
        vmconfig.vm.network :forwarded_port, host: "8181", guest: 8080 		 # Forward to Wildfly application port
        vmconfig.vm.network :forwarded_port, host: "10123", guest: 22, id: "ssh" # This avoid SSH overlaping port in the host
        vmconfig.vm.provider "virtualbox" do |vbox|
            vbox.customize ["modifyvm", :id, "--memory", "2048"]
            vbox.customize ["modifyvm", :id, "--name"  , "identity-node1"]
        end
        vmconfig.vm.provision "shell", privileged: false, inline: <<-SHELL
	    echo "Installing Open JDK 8 ..."
	    sudo echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
	    sudo add-apt-repository -y ppa:webupd8team/java
	    sudo apt-get update
	    sudo apt-get install -y oracle-java8-installer
	    sudo rm -rf /var/cache/oracle-jdk8-installer
	    export JAVA_HOME="/usr/lib/jvm/java-8-oracle"

	    echo "Downloading and configuring Wildfly App Server 10.0.0.Final ..."
	    export WILDFLY_VERSION="10.0.0.Final"
	    curl https://download.jboss.org/wildfly/$WILDFLY_VERSION/wildfly-$WILDFLY_VERSION.tar.gz | tar -xz
	    export JBOSS_HOME="/opt/wildfly"
	    sudo mv wildfly-$WILDFLY_VERSION $JBOSS_HOME
	    sudo $JBOSS_HOME/bin/add-user.sh admin Admin123 --silent
	    sudo cp -f /vagrant/nodes-config/standalone-ha.xml $JBOSS_HOME/standalone/configuration/
            sudo cp -r /vagrant/nodes-config/postgresql $JBOSS_HOME/modules/system/layers/base/org/
	    sudo sed -i "s|jboss.bind.address.management:127.0.0.1|jboss.bind.address.management:172.16.76.2|g" $JBOSS_HOME/standalone/configuration/standalone-ha.xml
	    sudo sed -i "s|jboss.bind.address:127.0.0.1|jboss.bind.address:172.16.76.2|g" $JBOSS_HOME/standalone/configuration/standalone-ha.xml
	    sudo sed -i "s|jboss.bind.address.private:127.0.0.1|jboss.bind.address.private:172.16.76.2|g" $JBOSS_HOME/standalone/configuration/standalone-ha.xml
	    sudo cp -f /vagrant/nodes-config/wildfly.conf /etc/default/wildfly
	    sudo cp -f /vagrant/nodes-config/wildfly-init-debian.sh /etc/init.d/wildfly
	    sudo cp -f /vagrant/nodes-config/wildfly-upstart.conf /etc/init/
	    sudo cp -f /vagrant/nodes-config/hiperium-identity.war $JBOSS_HOME/standalone/deployments/
	    sudo useradd -r -s /bin/false wildfly
	    sudo chown -R wildfly:wildfly $JBOSS_HOME

	    echo "Deploying Hiperium Identity Service ..."
	    sudo service wildfly start
        SHELL
    end

    # Put the VM in Vagrant Cache
    if Vagrant.has_plugin?("vagrant-cachier")
    	config.cache.scope = :box
    end
end
