# -*- mode: ruby -*-
# vi: set ft=ruby :

# # Vagrant 1.7+ automatically inserts a different
# # insecure keypair for each new VM created. The easiest way
# # to use the same keypair for all the machines is to disable
# # this feature and rely on the legacy insecure key.
# # config.ssh.insert_key = false
Vagrant.configure("2") do |config|

    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://atlas.hashicorp.com/search.
    config.vm.box = "ubuntu/trusty64"

    # Synced folder configuration 
    if (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
        config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=700,fmode=600"]
    else
        config.vm.synced_folder ".", "/vagrant"
    end

    # Common domain configuration
    config.vm.provider "virtualbox" do |domain|
	domain.customize ["modifyvm", :id, "--nic2", "hostonly"]
        domain.customize ["modifyvm", :id, "--hostonlyadapter2", "vboxnet1"]
    end

    # Machine-nodes specific definition
    config.vm.define "dev-identity-node1" do |vmconfig|
      	vmconfig.vm.hostname = "dev-identity-node1"
        vmconfig.vm.network :private_network, ip: "172.16.76.2", netmask: "28"
        vmconfig.vm.network :forwarded_port, host: "8181",  guest: 8080          # Forward to Wildfly application port
	vmconfig.vm.network :forwarded_port, host: "9991",  guest: 9990
        vmconfig.vm.network :forwarded_port, host: "10122", guest: 22, id: "ssh" # This avoid SSH overlaping port in the host
        vmconfig.vm.provider "virtualbox" do |vbox|
            vbox.customize ["modifyvm", :id, "--memory", "2048"]
            vbox.customize ["modifyvm", :id, "--name"  , "dev-identity-node1"]
        end
	vmconfig.vm.provision "shell", path: "bootstrap.sh"			 # Install Ansible via shell provisioning
	vmconfig.vm.provision "shell", inline: <<-SHELL				 # Install Docker via Ansible and deploy Hiperium Service
	    echo "Running Ansible Playbook ..."
	    PYTHONUNBUFFERED=1 ansible-playbook /vagrant/ansible/standalone.yml -c local
	    echo "Building and running Docker image ..."
	    docker --version
	    docker pull hiperium/hiperium-identity:v1
	    docker run -itd -p 8080:8080 -p 9990:9990 hiperium/hiperium-identity:v1 /opt/jboss/wildfly/bin/standalone.sh -c standalone-ha.xml -b 0.0.0.0 -bmanagement 0.0.0.0 -Djboss.node.name=identity-node1
        SHELL
    end

    # Put the VM in Vagrant Cache
    if Vagrant.has_plugin?("vagrant-cachier")
    	config.cache.scope = :box
    end
end
